version: "3"
services:
  blog:
    build: .
    environment:
      WAIT_HOSTS: postgres:5432, strapi:1337
      WAIT_HOSTS_TIMEOUT: 999
      STRAPI_API: strapi:1337
      STRAPI_USER: user@gmail.com
      STRAPI_PASSWORD: password
    ports:
      - "80:9000"
    depends_on:
      - strapi
      - postgres
    command: bash -c "/wait && yarn build && yarn serve"

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    volumes:
      - ./strapi-app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
