version: "3"
services:
  blog:
    build: .
    environment:
      WAIT_HOSTS: postgres:5432, strapi:1337
      WAIT_HOSTS_TIMEOUT: 999
    ports:
      - "80:9000"
    depends_on:
      - strapi
      - postgres
    command: bash -c "/wait && yarn build && yarn serve"

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: "${POSTGRES_DB}"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./strapi-app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
